### ISSUE TITLE
Too many arguments provide to function-like macro invocation

### ISSUE THREAD

**Issue by nobre84** [itsthejb/ObjcAssociatedObjectHelpers#10]
Hi! Great library, thanks!
I'm getting this compiler error when using Lazy readonly getters with collections as the expression, for instance:

`SYNTHESIZE_ASC_OBJ_LAZY_EXP(properties, @[@1 , @2, @3]);`

Any way around it ?

**Comment by itsthejb** [comment]
Hi there. This is super old, but I learnt more recently that it's possible to include comma-separated values in macros by adding additional parentheses around the value:

```
SYNTHESIZE_ASC_OBJ_LAZY_EXP(properties, (@[@1 , @2, @3]));
```

I should probably add this to the README at some point
